SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d'), PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM
(
    select SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE SALES_DATE >= '2022-03-01' and SALES_DATE <= '2022-03-31'
    union all
    SELECT SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE SALES_DATE >= '2022-03-01' and SALES_DATE <= '2022-03-31'
) as INTEGRATE
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;