SELECT YEAR(OS.SALES_DATE) as YEAR, MONTH(OS.SALES_DATE) as MONTH, 
COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS, 
ROUND(COUNT(DISTINCT U.USER_ID) / (SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE JOINED LIKE '%2021%'), 1) as PURCHASED_RATIO
FROM USER_INFO as U JOIN ONLINE_SALE as OS 
ON U.USER_ID = OS.USER_ID
WHERE YEAR(U.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC;