SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, FP.PRICE * SUM(FO.AMOUNT) as TOTAL_SALES
FROM FOOD_PRODUCT as FP JOIN FOOD_ORDER AS FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE YEAR(FO.PRODUCE_DATE) = 2022 and MONTH(FO.PRODUCE_DATE) = 5
GROUP BY FP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;

# SELECT PRODUCT_ID, PRODUCT_NAME, PRICE
# FROM FOOD_PRODUCT;

# SELECT *
# FROM FOOD_ORDER;