-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF as F,
    (SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL_ORDER FROM JULY GROUP BY FLAVOR) as FL_SUM
WHERE F.FLAVOR = FL_SUM.FLAVOR
ORDER BY F.TOTAL_ORDER + FL_SUM.TOTAL_ORDER DESC LIMIT 3;