WITH RECURSIVE HOURS AS (
    -- BASE
    SELECT 0 AS HOUR
    UNION ALL
    -- RECURSIVE
    SELECT HOUR + 1 FROM HOURS
    WHERE HOUR < 23
)

SELECT HOURS.HOUR AS HOUR, COUNT(AO.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS AS AO
RIGHT JOIN HOURS ON EXTRACT(HOUR FROM AO.DATETIME) = HOURS.HOUR
GROUP BY HOURS.HOUR
ORDER BY HOUR;