SELECT EXTRACT(HOUR from DATETIME) as HOUR, COUNT(ANIMAL_ID) as COUNT
FROM ANIMAL_OUTS
where EXTRACT(HOUR from DATETIME) >= 9 and EXTRACT(HOUR from DATETIME) < 20
group by EXTRACT(HOUR from DATETIME)
order by hour;